import { timingSafeEqual } from "node:crypto";
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { reviewEnvironmentRefusal } from "@/lib/review-mode";

/**
 * The wrapper every `/api/qa/*` route is built from.
 *
 * WHAT THIS SURFACE IS FOR. A browser cannot, on its own, make a match finish,
 * read an SMS, put a selection into suspension, or fund an account without a
 * payment provider. Those are not UI gaps — they are things that happen
 * elsewhere in the world. Without a way to make them happen locally, every
 * flow that depends on one stays untested in a browser forever, and the
 * status document fills up with `IMPLEMENTED_NOT_LIVE_TESTED` next to controls
 * customers use daily. This surface makes them happen, on a disposable
 * machine, through the same services the real triggers use.
 *
 * WHY IT IS SAFE, IN THE ORDER THE CHECKS RUN:
 *
 *   1. THE REVIEW GATE. `reviewEnvironmentRefusal()` requires
 *      `PLUTOBET_ENVIRONMENT=review`, `PLUTOBET_REVIEW_ADAPTERS=1`, no hosting
 *      platform variables, and NO live provider credentials anywhere in the
 *      environment. The last condition is the one that cannot be forged
 *      alongside the harm: a process able to reach Termii, Paystack or B2 is
 *      never a review process.
 *
 *   2. A PER-RUN KEY. `PLUTOBET_REVIEW_KEY` is 32 random bytes generated by
 *      `scripts/review-server.mjs` into a gitignored file, and the caller must
 *      present it in `x-plutobet-review-key`. This is what keeps the surface
 *      out of reach of a CUSTOMER on the review server itself — the browser
 *      suite signs in as a real player, and a player who could call these
 *      routes could mint money in the environment the money tests measure.
 *
 * 404, NOT 403, ON EVERY REFUSAL. A 403 confirms the route exists; the
 * security suite probes for exactly that and it should find nothing to
 * distinguish these paths from any other absent one. The refusal reason is
 * logged server-side, never returned.
 *
 * THE ROUTES ARE STILL IN THE PRODUCTION BUNDLE. That is stated plainly rather
 * than glossed: `next build` compiles them like any other route. What a
 * deployment does not have is an environment that satisfies condition 1 or a
 * key that satisfies condition 2, and `qa-route-refusal.acceptance.spec.ts`
 * asserts each condition independently rather than trusting the pair.
 */

const HEADER = "x-plutobet-review-key";

function keyMatches(supplied: string | null): boolean {
  const expected = process.env.PLUTOBET_REVIEW_KEY ?? "";
  // An unset key must never mean "everyone passes". This is the branch that
  // would turn a misconfiguration into an open door.
  if (expected.trim().length < 32) return false;
  if (!supplied) return false;
  const a = Buffer.from(expected, "utf8");
  const b = Buffer.from(supplied, "utf8");
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

/** Why this request may not use the QA surface, or `null` if it may. */
export function qaRefusal(request: NextRequest): string | null {
  const environment = reviewEnvironmentRefusal();
  if (environment) return environment;
  if (!keyMatches(request.headers.get(HEADER))) return "review key missing or wrong";
  return null;
}

export type QaHandler = (request: NextRequest) => Promise<NextResponse> | NextResponse;

/**
 * The answer for a verb a QA route does not implement.
 *
 * WHY THIS EXISTS. Next answers 405 for a method a route file does not export,
 * and it does that BEFORE any handler runs — so `GET /api/qa/fixtures` came
 * back 405 while `POST` came back 404, and the pair told an unauthenticated
 * stranger that the path exists. The whole point of answering 404 rather than
 * 403 is that a customer cannot tell this surface is there; a 405 undid it for
 * the cost of guessing one verb. Found by the security suite probing both verbs
 * on every path, which is why it probes both.
 *
 * Past the gate, 405 is the honest answer and reveals nothing: the caller
 * already holds the key.
 */
export function qaMethodNotAllowed(name: string) {
  return async (request: NextRequest): Promise<NextResponse> => {
    const refusal = qaRefusal(request);
    if (refusal) {
      console.warn(`[qa] refused ${name}: ${refusal}`);
      return new NextResponse(null, { status: 404 });
    }
    return NextResponse.json({ error: "METHOD_NOT_ALLOWED" }, { status: 405 });
  };
}

export function qaRoute(name: string, handler: QaHandler) {
  return async (request: NextRequest): Promise<NextResponse> => {
    const refusal = qaRefusal(request);
    if (refusal) {
      console.warn(`[qa] refused ${name}: ${refusal}`);
      // Indistinguishable from a route that was never built.
      return new NextResponse(null, { status: 404 });
    }
    try {
      return await handler(request);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(`[qa] ${name} failed: ${message}`);
      return NextResponse.json({ error: "QA_FAILED", message }, { status: 500 });
    }
  };
}
