import { createHmac, timingSafeEqual } from "node:crypto";
import { mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { assertReviewEnvironment } from "@/lib/review-mode";

/**
 * Disposable local object storage, standing in for Backblaze B2 on a review
 * server.
 *
 * WHY. The KYC upload is the one customer flow that leaves the database, and
 * `scripts/review-server.mjs` BLANKS `B2_*` on purpose (finding 31: a review
 * run was writing test files into the production bucket of customers'
 * identity documents). Correct, and it left the upload with nowhere to go, so
 * `/kyc` had no browser coverage and the manifest carried an
 * integration-boundary row that was really "we turned the backend off".
 *
 * This is a backend, not a bypass. Everything that makes the real path safe —
 * the content-type allow-list, the size cap, the SERVER-GENERATED key, the
 * refusal to sign outside the `kyc/` namespace, the short-lived signature —
 * lives in `storage.ts` and applies identically here. What changes is where
 * the bytes land: a directory this machine throws away instead of a bucket
 * holding real passports.
 *
 * THE SIGNED URL IS REALLY SIGNED. It would have been easier to return a bare
 * path and let the QA route serve anything asked for, and that would have
 * quietly deleted the control the browser test is there to exercise — a
 * reviewer's link that never expires and that anyone can guess is the actual
 * risk with identity documents. So the review URL carries an HMAC over key and
 * expiry under the server's own secret, and the route verifies it in constant
 * time before reading a byte.
 */

const ROOT = path.resolve("artifacts", "review-kyc");

/** Same five minutes the B2 path uses, for the same reason. */
const TTL_SECONDS = 300;

function fileFor(key: string): string {
  /*
   * The key is generated by `documentKey()` from a user id and random bytes,
   * so it cannot contain traversal — but this is the function that turns a
   * string into a filesystem path, and a path builder that trusts its input
   * because of what today's caller happens to pass is a path builder that will
   * be wrong after one refactor. Checked here, at the boundary.
   */
  if (!/^kyc\/[A-Za-z0-9._-]+\/[A-Za-z0-9._-]+$/.test(key)) {
    throw new Error("refusing a document key that is not a plain kyc/<user>/<file> path");
  }
  const resolved = path.resolve(ROOT, key);
  if (!resolved.startsWith(ROOT + path.sep)) {
    throw new Error("refusing a document key that escapes the review store");
  }
  return resolved;
}

function secret(): string {
  /*
   * AUTH_SECRET, which `review-server.mjs` generates fresh per machine into a
   * gitignored file. Restarting the server therefore invalidates every
   * outstanding review link, which is the correct behaviour for a link to
   * somebody's identity document and happens to make the expiry test easy.
   */
  const value = process.env.AUTH_SECRET;
  if (!value) throw new Error("AUTH_SECRET is required to sign review document URLs");
  return value;
}

function signature(key: string, expiresAt: number): string {
  return createHmac("sha256", secret()).update(`${key}:${expiresAt}`).digest("hex");
}

export function putReviewDocument(key: string, body: Uint8Array): void {
  assertReviewEnvironment("review KYC storage");
  const file = fileFor(key);
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, body);
}

export function reviewDocumentExists(key: string): boolean {
  assertReviewEnvironment("review KYC storage");
  try {
    return statSync(fileFor(key)).isFile();
  } catch {
    return false;
  }
}

export function deleteReviewDocument(key: string): void {
  assertReviewEnvironment("review KYC storage");
  rmSync(fileFor(key), { force: true });
}

/** A short-lived, genuinely signed link to one stored document. */
export function reviewDocumentUrl(key: string, ttlSeconds = TTL_SECONDS): string {
  assertReviewEnvironment("review KYC storage");
  const expiresAt = Math.floor(Date.now() / 1000) + Math.min(ttlSeconds, 3600);
  const query = new URLSearchParams({
    key,
    expires: String(expiresAt),
    signature: signature(key, expiresAt),
  });
  return `/api/qa/kyc-document?${query.toString()}`;
}

export class ReviewDocumentLinkError extends Error {
  constructor(readonly reason: "EXPIRED" | "BAD_SIGNATURE" | "MISSING") {
    super(reason);
    this.name = "ReviewDocumentLinkError";
  }
}

/** Verifies a review link and returns the bytes. Throws on anything wrong. */
export function readSignedReviewDocument(params: {
  key: string;
  expires: string;
  signature: string;
}): Uint8Array {
  assertReviewEnvironment("review KYC storage");
  const expiresAt = Number(params.expires);
  if (!Number.isFinite(expiresAt)) throw new ReviewDocumentLinkError("BAD_SIGNATURE");

  const expected = Buffer.from(signature(params.key, expiresAt), "utf8");
  const supplied = Buffer.from(params.signature, "utf8");
  // Length first: timingSafeEqual throws on a mismatch rather than returning
  // false, and a thrown comparison is a comparison that did not happen.
  if (expected.length !== supplied.length || !timingSafeEqual(expected, supplied)) {
    throw new ReviewDocumentLinkError("BAD_SIGNATURE");
  }
  // Expiry AFTER the signature check, so an unsigned guess learns nothing
  // about which keys exist from the shape of the refusal.
  if (expiresAt * 1000 < Date.now()) throw new ReviewDocumentLinkError("EXPIRED");

  try {
    return readFileSync(fileFor(params.key));
  } catch {
    throw new ReviewDocumentLinkError("MISSING");
  }
}
